apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-diff-front
  namespace: team-diff
  labels:
    app: team-diff-front
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: team-diff-front
      
  template:
    metadata:
      labels:
        app: team-diff-front
        tier: team-diff-front
    spec:
      containers:
        - name: team-diff
          image: europe-west1-docker.pkg.dev/lem-aap-dev-applibusiness-prj/lem-bs-dev-tdf-registry-001/team-diff-api:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: team-diff-front
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2"

---
apiVersion: v1
kind: Service
metadata:
  name: ilb-svc-front
  namespace: team-diff
  labels:
    app: team-diff-front
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: team-diff-front
    tier: team-diff-front
  ports:
  - name: tcp-port
    protocol: TCP
    port: 80
    targetPort: 80



----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-diff-api
  namespace: team-diff
  labels:
    app: team-diff-api
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: team-diff-api
      
  template:
    metadata:
      labels:
        app: team-diff-api
        tier: team-diff-api
    spec:
      containers:
        - name: team-diff-api
          image: europe-west1-docker.pkg.dev/lem-aap-dev-applibusiness-prj/lem-bs-dev-tdf-registry-001/team-diff-api:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: team-diff-api
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2"

---
apiVersion: v1
kind: Service
metadata:
  name: ilb-svc-api
  namespace: team-diff
  labels:
    app: team-diff-api
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: team-diff-api
    tier: team-diff-api
  ports:
  - name: tcp-port
    protocol: TCP
    port: 80
    targetPort: 80