controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_doc:
    path: /docs
    controller: api_platform.swagger_ui.action
api_refresh_token:
    path: /api/token/refresh
auth:
    path: /auth
    methods: ['POST']

